development:
  adapter: sqlite3
  database: db/quotes_dev.sqlite.db

test:
  adapter: sqlite3
  database: db/quotes_test.sqlite.db

production:
  adapter: mysql2
  encoding: utf8
  pool: 5
  timeout: 5000
  database: ta
  username: ta
  password: H2S-Wr-m
  host: 198.199.96.235
